application: librarywebchat
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /libs
  static_dir: libs

- url: /assets
  static_dir: assets

- url: /test.*
  script: gaeunit.py

- url: /.*
  script: chatapp.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: django
  version: "1.2"
