this.dopamine=this.dopamine||{};
(function(b){function a(){if(arguments.callee._singletonInstance)return arguments.callee._singletonInstance;arguments.callee._singletonInstance=this}a.prototype.append=function(a,d,f,e,h,g,j,k){a={key:a,values:JSON.stringify(d)};"undefined"!==typeof h&&(a.action_url=h,a.title=g,a.message=j,"undefined"!==typeof k&&null!==k&&(a.my_push_url=k));b.ajax({url:"/objstore/append/append",type:"POST",data:a,dataType:"json",success:f,error:e})};a.prototype.get=function(a,d,f,e){if("undefined"===typeof d||null===
d||""===d)d=0;b.ajax({url:"/objstore/append/get",type:"POST",data:{key:a,start_index:d},dataType:"json",success:f,error:e})};a.prototype.addPushUrl=function(a,b,f,e){this._addRemPushUrl("/objstore/append/add_push_url",a,b,f,e)};a.prototype.removePushUrl=function(a,b,f,e){this._addRemPushUrl("/objstore/append/rem_push_url",a,b,f,e)};a.prototype._addRemPushUrl=function(a,d,f,e,h){b.ajax({url:a,type:"POST",data:{key:d,push_url:f},dataType:"json",success:e,error:h})};Object.defineProperty(dopamine,"appendStore",
{get:function(){return new a}})})(jQuery);this.dopamine=this.dopamine||{};
(function(){Object.defineProperty(dopamine,"ui",{get:function(){return new Ui}});dopamine._adrenaline="undefined"!==typeof window.adrenaline?window.adrenaline:null;dopamine.__commandQueue=[];dopamine._callbackId=Math.floor(2E9*Math.random());dopamine._callbacks={};dopamine._callbackStatus={NO_RESULT:0,OK:1,CLASS_NOT_FOUND_EXCEPTION:2,ILLEGAL_ACCESS_EXCEPTION:3,INSTANTIATION_EXCEPTION:4,MALFORMED_URL_EXCEPTION:5,IO_EXCEPTION:6,INVALID_ACTION:7,JSON_EXCEPTION:8,ERROR:9};dopamine._execIframe=null;dopamine.__callbackSuccess=
function(b,a){if(dopamine._callbacks[b]){if(a.status==dopamine._callbackStatus.OK)try{dopamine._callbacks[b].success&&dopamine._callbacks[b].success(a.message)}catch(c){console.log("Error in success callback: "+b+" = "+c)}a.keepCallback||delete dopamine._callbacks[b]}};dopamine.__callbackError=function(b,a){if(dopamine._callbacks[b]){try{dopamine._callbacks[b].fail&&dopamine._callbacks[b].fail(a.message)}catch(c){console.log("Error in success callback: "+b+" = "+c)}a.keepCallback||delete dopamine._callbacks[b]}};
dopamine.addConstructor=function(b){try{b()}catch(a){console.log("Failed to run constructor: "+a)}};dopamine.getExecIframe=function(){if(dopamine._execIframe)return dopamine._execIframe;var b=document.createElement("IFRAME");b.style.display="none";document.body.appendChild(b);return dopamine._execIframe=b};dopamine.iOSExec=function(b,a,c,d,f){try{var e=c+dopamine._callbackId++,h=JSON.stringify(f);if(b||a)dopamine._callbacks[e]={success:b,fail:a};dopamine.__commandQueue.push(JSON.stringify([e,c,d,
h]));dopamine.getExecIframe().src="adrenaline://ready"}catch(g){console.log("iOSExec error: "+g)}};dopamine.exec=function(b,a,c,d,f){if(dopamine.utils.isAdrenalineIos())return dopamine.iOSExec(b,a,c,d,f);try{var e=c+dopamine._callbackId++,h=JSON.stringify(f);if(b||a)dopamine._callbacks[e]={success:b,fail:a};window._cordovaExec.exec(c,d,e,h)}catch(g){console.log("iOSExec error: "+g)}}})(jQuery);this.dopamine=this.dopamine||{};
(function(b){function a(){if(arguments.callee._singletonInstance)return arguments.callee._singletonInstance;arguments.callee._singletonInstance=this;this._flushOnWrite=!1;this._deviceId=null;this._workerRunning=!1;this.onobjectposted=null;var a=localStorage.getItem(c),b={};null===a||"undefined"===typeof a?this._onUpdate(0,d,b):(b=JSON.parse(a),b.version!==d&&this._onUpdate(b.version,d,b));this._flush()}var c=".adrenaline.objstore.metadata",d=1;a.prototype._onUpdate=function(a,b,d){if(0===a&&(a=localStorage.getItem("deviceid"),
null!==a&&(localStorage.setItem(".adrenaline.objstore.deviceid",a),this._deviceId=null),a=localStorage.getItem("adrenalineServerQueue"),null!==a)){a=JSON.parse(a);for(var g=0;g<a.length;g++){var j=a[g];this.setItem(j.key,j.value)}}d.vesrion=b;b=JSON.stringify(d);localStorage.setItem(c,b)};a.prototype._flushThread=function(){var a=this._squeueFront();if(null===a)this._workerRunning=!1;else{this._workerRunning=!0;a.value=JSON.stringify(a.value);var c=this;b.ajax({url:"/objstore/set_item",type:"POST",
data:a,dataType:"json",success:function(b){if("ok"===b["return"]){b.key===a.key&&c._squeuePop();if(null!==c.onobjectposted)c.onobjectposted(b.key,!1);c._flushThread()}else{if(null!==c.onobjectposted)c.onobjectposted(b.key,!0);c._workerRunning=!1}},error:function(){if(null!==c.onobjectposted)c.onobjectposted(a.key,!0);c._workerRunning=!1}})}};a.prototype._flush=function(){this._workerRunning||this._flushThread()};a.prototype._getUpdatedUuid=function(a){"undefined"===typeof a&&(a=this._getDeviceId());
return a};a.prototype._createLocalKey=function(a,b){b=this._getUpdatedUuid(b);return b+"-"+a};a.prototype._getDeviceId=function(){if(null!==this._deviceId)return this._deviceId;var a=localStorage.getItem(".adrenaline.objstore.deviceid");null===a&&(a=dopamine.utils.getNewId(),localStorage.setItem(".adrenaline.objstore.deviceid",a));return this._deviceId=a};a.prototype.getDefaultUuid=function(){return this._getDeviceId()};a.prototype.setItem=function(a,b,c){var d=this._createLocalKey(a,c);c=this._getUpdatedUuid(c);
localStorage.setItem(d,JSON.stringify(b));this._squeuePush({key:a,value:b,uuid:c});this._flushOnWrite&&this._flush()};a.prototype.getItem=function(a,b){var c=this._createLocalKey(a,b),c=localStorage.getItem(c);return null===c||"undefined"===typeof c?null:JSON.parse(c)};a.prototype.removeItem=function(a,c){var b=this._createLocalKey(a,c);localStorage.removeItem(b)};a.prototype.disableFlushOnWrite=function(){this._flushOnWrite=!1};a.prototype.enableFlushOnWrite=function(){this._flushOnWrite=!0;this._flush()};
a.prototype.hasPendingData=function(){return 0<this.pendingDataCount()};a.prototype.pendingDataCount=function(){return this._readServerQueue().length};a.prototype._readServerQueue=function(){ret=localStorage.getItem(".adrenaline.objstore.serverQueue");return null===ret?[]:JSON.parse(ret)};a.prototype._writeServerQueue=function(a){localStorage.setItem(".adrenaline.objstore.serverQueue",JSON.stringify(a))};a.prototype._squeuePush=function(a){var c=this._readServerQueue(),b=!1;if(2<=c.length){var d=
c.length-1;c[d].key===a.key&&c[d].uuid===a.uuid&&(c[d].value=a.value,b=!0)}b||c.push(a);this._writeServerQueue(c)};a.prototype._squeueFront=function(){var a=this._readServerQueue();return 0===a.length?null:a.shift()};a.prototype._squeuePop=function(){var a=this._readServerQueue();0!==a.length&&(a.shift(),this._writeServerQueue(a))};Object.defineProperty(dopamine,"objStore",{get:function(){return new a}})})(jQuery);this.dopamine=this.dopamine||{};
(function(){function b(){if(arguments.callee._singletonInstance)return arguments.callee._singletonInstance;arguments.callee._singletonInstance=this}b.prototype.requestFullscreen=function(a){var c={toast:!0,button:!0};"undefined"!==typeof a&&(c.toast=a);dopamine.exec(null,null,"FullScreenPlugin","requestFullscreen",[c])};b.prototype.cancelFullscreen=function(){dopamine.exec(null,null,"FullScreenPlugin","cancelFullscreen",[])};Object.defineProperty(dopamine,"plugins",{get:function(){return new b}})})(jQuery);
this.dopamine=this.dopamine||{};
(function(){function b(){if(arguments.callee._singletonInstance)return arguments.callee._singletonInstance;arguments.callee._singletonInstance=this}b.prototype.isoTime=function(){return JSON.parse(JSON.stringify(new Date))};b.prototype.isoDate=function(){var a=new Date,c=a.getFullYear()+"",b=a.getMonth()+1+"",a=a.getDate()+"";1===b.length&&(b="0"+b);1===a.length&&(a="0"+a);return c+"-"+b+"-"+a};b.prototype.getNewId=function(){var a="";if("undefined"!==typeof window.crypto&&"undefined"!==typeof window.crypto.getRandomValues){var c=
new Uint32Array(8);window.crypto.getRandomValues(c);for(idx=0;idx<c.length;idx++)a+=c[idx].toString(16)}else for(c=0;36>c;c++)a+="0123456789abcdef".substr(Math.floor(16*Math.random()),1);return a};b.prototype.getUrlParam=function(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b++)if(c[b].split("=")[0]===a)return decodeURIComponent(c[b].split("=")[1]);return null};b.prototype.addShortcut=function(a,b,d){if(null===dopamine._adrenaline||"undefined"===typeof dopamine._adrenaline.addShortCut)return!1;
"https://"===b.substring(0,8)&&(b="adrenalines://"+b.substring(8));"http://"===b.substring(0,7)&&(b="adrenaline://"+b.substring(7));dopamine._adrenaline.addShortCut(a,b,d);return!0};b.prototype.isAdrenalineAndroid=function(){return"undefined"!==typeof window._cordovaExec};b.prototype.isAdrenalineIos=function(){for(var a=["iPad","iPhone","iPod","iPhone Simulator","iPad Simulator"],b=0;b<a.length;b++)if(navigator.platform===a[b])return 0<=navigator.userAgent.indexOf("Adrenaline");return!1};Object.defineProperty(dopamine,
"utils",{get:function(){return new b}})})(jQuery);this.dopamine=this.dopamine||{};
(function(){function b(){if(arguments.callee._singletonInstance)return arguments.callee._singletonInstance;arguments.callee._singletonInstance=this;this._webPush="undefined"!==typeof window.webPush?window.webPush:null;this._pushUrlCbQueue=[]}b.prototype.requestPushUrl=function(a){if(this.hasPush())if(dopamine.utils.isAdrenalineIos()){var b=localStorage.getItem(".adrenaline.webpush.pushurl");"undefined"!==typeof b&&null!==b&&""!==b?setTimeout(function(){a(b)},0):dopamine.exec(function(b){localStorage.setItem(".adrenaline.webpush.pushurl",
b);a(b)},null,"WebPush","requestPushUrl",[])}else null!==this._webPush&&(this._handleCheckPermission(!0),this._pushUrlCbQueue.push(a))};b.prototype.hasPush=function(){return null!==this._webPush||dopamine.utils.isAdrenalineIos()};b.prototype._invokeCallbacks=function(a){for(;0<this._pushUrlCbQueue.length;){var b=this._pushUrlCbQueue.shift();localStorage.setItem(".adrenaline.webpush.pushurl",a);b(a)}};b.prototype._requestPermissionCb=function(){this._handleCheckPermission(!1)};b.prototype._requestPushUrlCb=
function(a){this._invokeCallbacks(a)};b.prototype._invokeInBackground=function(a){var b=this;setTimeout(function(){b._invokeCallbacks(a)},0)};b.prototype._handleCheckPermission=function(a){var b=localStorage.getItem(".adrenaline.webpush.pushurl");"undefined"!==typeof b&&null!==b&&""!==b?this._invokeInBackground(b):(b=this._webPush.checkPermission(),1===b?a&&this._webPush.requestPermission("dopamine.webPush._requestPermissionCb"):0===b?this._webPush.requestPushUrl("dopamine.webPush._requestPushUrlCb"):
2===b&&this._invokeInBackground(null))};Object.defineProperty(dopamine,"webPush",{get:function(){return new b}})})(jQuery);
